nelmio_api_doc:
    areas:
        path_patterns: [ ^/api ]
    documentation:
        info:
            title: Article generator 
            description: This project gives you hand to generate automatically articles and images using openAI API
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []